
name: Release Gold

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Zip Generator
        uses: thedoctor0/zip-release@master
        with:
          filename: 'Explosive_RPG-Blood_War_Gold.zip'
          path: './Output ./Build ./LICENSE ./README.md'
          exclusions: '*.gitignore* *Projecte2.sln* ./.github ./Docs ./Game'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: gold
          name: Blood War Gold
         
          artifacts: "Explosive_RPG-Blood_War_Gold.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
